name: Publish Module

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        description: "Name of the module (e.g., 'alert')"
        required: true
        type: string
      MODULE_TYPE:
        description: "Type of the module (e.g., 'sumologic')"
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  create-release-tags:
    name: Create Semantic Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git creds
        run: |
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"

      - name: Tag ${{ inputs.MODULE_TYPE }} ${{ inputs.MODULE_NAME }} module
        id: tag
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          major_pattern: "(major-${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }})"
          minor_pattern: "(minor-${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }})"
          change_path: "tools/${{ inputs.MODULE_TYPE }}/${{ inputs.MODULE_NAME }}"
          namespace: "${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }}"
          bump_each_commit: true

      - name: Output version
        run: echo "${{ steps.tag.outputs.version }}"
        shell: bash

      - name: Tag repo
        id: tag-repo
        run: |
          if git rev-parse ${{ steps.tag.outputs.version }}-${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }} >/dev/null 2>&1; then
            echo "Tag already exists, skipping tagging."
          else
            git tag -a ${{ steps.tag.outputs.version }}-${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }} -m "Release ${{ steps.tag.outputs.version }}-${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }}"
            git push origin ${{ steps.tag.outputs.version }}-${{ inputs.MODULE_TYPE }}-${{ inputs.MODULE_NAME }}
          fi
